### PR TITLE
Add Soumyadip Majumder to Contributors list

### PR DESCRIPTION
**Pull request by SoumyadipYT-OSS**

### CODE REVIEW

**Comment by SoumyadipYT-OSS** [comment]
I want to contribute in this repository. I want to add an exercise and modify the code. @jamesmontemagno @microsoftopensource

**Comment by SoumyadipYT-OSS** [comment]
Dear Microsoft team,
     Can you provide me the step-by-step guidance to contribute on open-source project on Microsoft GitHub?
Thanking you,
Soumyadip Majumder
________________________________

**Comment by SoumyadipYT-OSS** [comment]
I want to contribute by myself, what should I do?

**Comment by jamesmontemagno** [comment]
You can make a PR to the repo if you have changes or modifications you would like to make.

**Comment by SoumyadipYT-OSS** [comment]
@jamesmontemagno Interested to contribute, where I can create a PR for this repository?

**Comment by SoumyadipYT-OSS** [comment]
I am new in this community somebody guide me

**Pull request closed without merging**
